mod anagram;
mod array_consecutive_missing_number;
mod calculate_list_max_items_difference;
mod calculate_no_overlaps;
mod fizzbuzz;
mod linear_searching;
mod mistery_algorithm;
mod reverse_words_in_a_sentence;
mod sort_strings;
mod string_capitalize;
mod string_reverse;
pub use array_consecutive_missing_number::find_missing_number;
pub use calculate_list_max_items_difference::calculate_list_max_items_difference;
pub use calculate_no_overlaps::calculate_no_overlaps;
pub use fizzbuzz::{execute_fizzbuzz, print_controller};
pub use linear_searching::linear_searching;
pub use mistery_algorithm::mistery_algorithm;
pub use reverse_words_in_a_sentence::reverse_words_in_a_sentence;
pub use string_capitalize::{string_capitalize_one, string_capitalize_two};
pub use string_reverse::{string_reverse_one, string_reverse_two};
mod gigasecond;
pub use anagram::find_anagrams;
pub use gigasecond::{calculate_date_one, calculate_date_two};
pub use sort_strings::sort_strings;
